inherit_from:
  - .rubocop_todo.yml
  - .rubocop_rspec_base.yml

AllCops:
  TargetRubyVersion: 2.4

# All these metrics should go down over time.

Metrics/ClassLength:
  Max: 279

Metrics/CyclomaticComplexity:
  Max: 18

Layout/LineLength:
  Max: 193
  Exclude:
    - features/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 49

Metrics/AbcSize:
  Max: 47

Metrics/BlockLength:
  Max: 45
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Max: 220
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Max: 19
